 # Vestimenta RGB 64 colores
name: RGB
rules:
  - image: pix000.png
    when:
      black: 0
      red: 0
      green: 0
      blue: 0
  - image: pix000.png
    when:
      black: 1
      red: 0
      green: 0
      blue: 0
  - image: sel000.png
    when:
      black: 2
      red: 0
      green: 0
      blue: 0
  - image: pix001.png
    when:
      black: 0
      red: 0
      green: 0
      blue: 1
  - image: pix001.png
    when:
      black: 1
      red: 0
      green: 0
      blue: 1
  - image: sel001.png
    when:
      black: 2
      red: 0
      green: 0
      blue: 1
  - image: pix002.png
    when:
      black: 0
      red: 0
      green: 0
      blue: 2
  - image: pix002.png
    when:
      black: 1
      red: 0
      green: 0
      blue: 2
  - image: sel002.png
    when:
      black: 2
      red: 0
      green: 0
      blue: 2
  - image: pix003.png
    when:
      black: 0
      red: 0
      green: 0
      blue: 3
  - image: pix003.png
    when:
      black: 1
      red: 0
      green: 0
      blue: 3
  - image: sel003.png
    when:
      black: 2
      red: 0
      green: 0
      blue: 3
  - image: pix010.png
    when:
      black: 0
      red: 0
      green: 1
      blue: 0
  - image: pix010.png
    when:
      black: 1
      red: 0
      green: 1
      blue: 0
  - image: sel010.png
    when:
      black: 2
      red: 0
      green: 1
      blue: 0
  - image: pix011.png
    when:
      black: 0
      red: 0
      green: 1
      blue: 1
  - image: pix011.png
    when:
      black: 1
      red: 0
      green: 1
      blue: 1
  - image: sel011.png
    when:
      black: 2
      red: 0
      green: 1
      blue: 1
  - image: pix012.png
    when:
      black: 0
      red: 0
      green: 1
      blue: 2
  - image: pix012.png
    when:
      black: 1
      red: 0
      green: 1
      blue: 2
  - image: sel012.png
    when:
      black: 2
      red: 0
      green: 1
      blue: 2
  - image: pix013.png
    when:
      black: 0
      red: 0
      green: 1
      blue: 3
  - image: pix013.png
    when:
      black: 1
      red: 0
      green: 1
      blue: 3
  - image: sel013.png
    when:
      black: 2
      red: 0
      green: 1
      blue: 3
  - image: pix020.png
    when:
      black: 0
      red: 0
      green: 2
      blue: 0
  - image: pix020.png
    when:
      black: 1
      red: 0
      green: 2
      blue: 0
  - image: sel020.png
    when:
      black: 2
      red: 0
      green: 2
      blue: 0
  - image: pix021.png
    when:
      black: 0
      red: 0
      green: 2
      blue: 1
  - image: pix021.png
    when:
      black: 1
      red: 0
      green: 2
      blue: 1
  - image: sel021.png
    when:
      black: 2
      red: 0
      green: 2
      blue: 1
  - image: pix022.png
    when:
      black: 0
      red: 0
      green: 2
      blue: 2
  - image: pix022.png
    when:
      black: 1
      red: 0
      green: 2
      blue: 2
  - image: sel022.png
    when:
      black: 2
      red: 0
      green: 2
      blue: 2
  - image: pix023.png
    when:
      black: 0
      red: 0
      green: 2
      blue: 3
  - image: pix023.png
    when:
      black: 1
      red: 0
      green: 2
      blue: 3
  - image: sel023.png
    when:
      black: 2
      red: 0
      green: 2
      blue: 3
  - image: pix030.png
    when:
      black: 0
      red: 0
      green: 3
      blue: 0
  - image: pix030.png
    when:
      black: 1
      red: 0
      green: 3
      blue: 0
  - image: sel030.png
    when:
      black: 2
      red: 0
      green: 3
      blue: 0
  - image: pix031.png
    when:
      black: 0
      red: 0
      green: 3
      blue: 1
  - image: pix031.png
    when:
      black: 1
      red: 0
      green: 3
      blue: 1
  - image: sel031.png
    when:
      black: 2
      red: 0
      green: 3
      blue: 1
  - image: pix032.png
    when:
      black: 0
      red: 0
      green: 3
      blue: 2
  - image: pix032.png
    when:
      black: 1
      red: 0
      green: 3
      blue: 2
  - image: sel032.png
    when:
      black: 2
      red: 0
      green: 3
      blue: 2
  - image: pix033.png
    when:
      black: 0
      red: 0
      green: 3
      blue: 3
  - image: pix033.png
    when:
      black: 1
      red: 0
      green: 3
      blue: 3
  - image: sel033.png
    when:
      black: 2
      red: 0
      green: 3
      blue: 3
  - image: pix100.png
    when:
      black: 0
      red: 1
      green: 0
      blue: 0
  - image: pix100.png
    when:
      black: 1
      red: 1
      green: 0
      blue: 0
  - image: sel100.png
    when:
      black: 2
      red: 1
      green: 0
      blue: 0
  - image: pix101.png
    when:
      black: 0
      red: 1
      green: 0
      blue: 1
  - image: pix101.png
    when:
      black: 1
      red: 1
      green: 0
      blue: 1
  - image: sel101.png
    when:
      black: 2
      red: 1
      green: 0
      blue: 1
  - image: pix102.png
    when:
      black: 0
      red: 1
      green: 0
      blue: 2
  - image: pix102.png
    when:
      black: 1
      red: 1
      green: 0
      blue: 2
  - image: sel102.png
    when:
      black: 2
      red: 1
      green: 0
      blue: 2
  - image: pix103.png
    when:
      black: 0
      red: 1
      green: 0
      blue: 3
  - image: pix103.png
    when:
      black: 1
      red: 1
      green: 0
      blue: 3
  - image: sel103.png
    when:
      black: 2
      red: 1
      green: 0
      blue: 3
  - image: pix110.png
    when:
      black: 0
      red: 1
      green: 1
      blue: 0
  - image: pix110.png
    when:
      black: 1
      red: 1
      green: 1
      blue: 0
  - image: sel110.png
    when:
      black: 2
      red: 1
      green: 1
      blue: 0
  - image: pix111.png
    when:
      black: 0
      red: 1
      green: 1
      blue: 1
  - image: pix111.png
    when:
      black: 1
      red: 1
      green: 1
      blue: 1
  - image: sel111.png
    when:
      black: 2
      red: 1
      green: 1
      blue: 1
  - image: pix112.png
    when:
      black: 0
      red: 1
      green: 1
      blue: 2
  - image: pix112.png
    when:
      black: 1
      red: 1
      green: 1
      blue: 2
  - image: sel112.png
    when:
      black: 2
      red: 1
      green: 1
      blue: 2
  - image: pix113.png
    when:
      black: 0
      red: 1
      green: 1
      blue: 3
  - image: pix113.png
    when:
      black: 1
      red: 1
      green: 1
      blue: 3
  - image: sel113.png
    when:
      black: 2
      red: 1
      green: 1
      blue: 3
  - image: pix120.png
    when:
      black: 0
      red: 1
      green: 2
      blue: 0
  - image: pix120.png
    when:
      black: 1
      red: 1
      green: 2
      blue: 0
  - image: sel120.png
    when:
      black: 2
      red: 1
      green: 2
      blue: 0
  - image: pix121.png
    when:
      black: 0
      red: 1
      green: 2
      blue: 1
  - image: pix121.png
    when:
      black: 1
      red: 1
      green: 2
      blue: 1
  - image: sel121.png
    when:
      black: 2
      red: 1
      green: 2
      blue: 1
  - image: pix122.png
    when:
      black: 0
      red: 1
      green: 2
      blue: 2
  - image: pix122.png
    when:
      black: 1
      red: 1
      green: 2
      blue: 2
  - image: sel122.png
    when:
      black: 2
      red: 1
      green: 2
      blue: 2
  - image: pix123.png
    when:
      black: 0
      red: 1
      green: 2
      blue: 3
  - image: pix123.png
    when:
      black: 1
      red: 1
      green: 2
      blue: 3
  - image: sel123.png
    when:
      black: 2
      red: 1
      green: 2
      blue: 3
  - image: pix130.png
    when:
      black: 0
      red: 1
      green: 3
      blue: 0
  - image: pix130.png
    when:
      black: 1
      red: 1
      green: 3
      blue: 0
  - image: sel130.png
    when:
      black: 2
      red: 1
      green: 3
      blue: 0
  - image: pix131.png
    when:
      black: 0
      red: 1
      green: 3
      blue: 1
  - image: pix131.png
    when:
      black: 1
      red: 1
      green: 3
      blue: 1
  - image: sel131.png
    when:
      black: 2
      red: 1
      green: 3
      blue: 1
  - image: pix132.png
    when:
      black: 0
      red: 1
      green: 3
      blue: 2
  - image: pix132.png
    when:
      black: 1
      red: 1
      green: 3
      blue: 2
  - image: sel132.png
    when:
      black: 2
      red: 1
      green: 3
      blue: 2
  - image: pix133.png
    when:
      black: 0
      red: 1
      green: 3
      blue: 3
  - image: pix133.png
    when:
      black: 1
      red: 1
      green: 3
      blue: 3
  - image: sel133.png
    when:
      black: 2
      red: 1
      green: 3
      blue: 3
  - image: pix200.png
    when:
      black: 0
      red: 2
      green: 0
      blue: 0
  - image: pix200.png
    when:
      black: 1
      red: 2
      green: 0
      blue: 0
  - image: sel200.png
    when:
      black: 2
      red: 2
      green: 0
      blue: 0
  - image: pix201.png
    when:
      black: 0
      red: 2
      green: 0
      blue: 1
  - image: pix201.png
    when:
      black: 1
      red: 2
      green: 0
      blue: 1
  - image: sel201.png
    when:
      black: 2
      red: 2
      green: 0
      blue: 1
  - image: pix202.png
    when:
      black: 0
      red: 2
      green: 0
      blue: 2
  - image: pix202.png
    when:
      black: 1
      red: 2
      green: 0
      blue: 2
  - image: sel202.png
    when:
      black: 2
      red: 2
      green: 0
      blue: 2
  - image: pix203.png
    when:
      black: 0
      red: 2
      green: 0
      blue: 3
  - image: pix203.png
    when:
      black: 1
      red: 2
      green: 0
      blue: 3
  - image: sel203.png
    when:
      black: 2
      red: 2
      green: 0
      blue: 3
  - image: pix210.png
    when:
      black: 0
      red: 2
      green: 1
      blue: 0
  - image: pix210.png
    when:
      black: 1
      red: 2
      green: 1
      blue: 0
  - image: sel210.png
    when:
      black: 2
      red: 2
      green: 1
      blue: 0
  - image: pix211.png
    when:
      black: 0
      red: 2
      green: 1
      blue: 1
  - image: pix211.png
    when:
      black: 1
      red: 2
      green: 1
      blue: 1
  - image: sel211.png
    when:
      black: 2
      red: 2
      green: 1
      blue: 1
  - image: pix212.png
    when:
      black: 0
      red: 2
      green: 1
      blue: 2
  - image: pix212.png
    when:
      black: 1
      red: 2
      green: 1
      blue: 2
  - image: sel212.png
    when:
      black: 2
      red: 2
      green: 1
      blue: 2
  - image: pix213.png
    when:
      black: 0
      red: 2
      green: 1
      blue: 3
  - image: pix213.png
    when:
      black: 1
      red: 2
      green: 1
      blue: 3
  - image: sel213.png
    when:
      black: 2
      red: 2
      green: 1
      blue: 3
  - image: pix220.png
    when:
      black: 0
      red: 2
      green: 2
      blue: 0
  - image: pix220.png
    when:
      black: 1
      red: 2
      green: 2
      blue: 0
  - image: sel220.png
    when:
      black: 2
      red: 2
      green: 2
      blue: 0
  - image: pix221.png
    when:
      black: 0
      red: 2
      green: 2
      blue: 1
  - image: pix221.png
    when:
      black: 1
      red: 2
      green: 2
      blue: 1
  - image: sel221.png
    when:
      black: 2
      red: 2
      green: 2
      blue: 1
  - image: pix222.png
    when:
      black: 0
      red: 2
      green: 2
      blue: 2
  - image: pix222.png
    when:
      black: 1
      red: 2
      green: 2
      blue: 2
  - image: sel222.png
    when:
      black: 2
      red: 2
      green: 2
      blue: 2
  - image: pix223.png
    when:
      black: 0
      red: 2
      green: 2
      blue: 3
  - image: pix223.png
    when:
      black: 1
      red: 2
      green: 2
      blue: 3
  - image: sel223.png
    when:
      black: 2
      red: 2
      green: 2
      blue: 3
  - image: pix230.png
    when:
      black: 0
      red: 2
      green: 3
      blue: 0
  - image: pix230.png
    when:
      black: 1
      red: 2
      green: 3
      blue: 0
  - image: sel230.png
    when:
      black: 2
      red: 2
      green: 3
      blue: 0
  - image: pix231.png
    when:
      black: 0
      red: 2
      green: 3
      blue: 1
  - image: pix231.png
    when:
      black: 1
      red: 2
      green: 3
      blue: 1
  - image: sel231.png
    when:
      black: 2
      red: 2
      green: 3
      blue: 1
  - image: pix232.png
    when:
      black: 0
      red: 2
      green: 3
      blue: 2
  - image: pix232.png
    when:
      black: 1
      red: 2
      green: 3
      blue: 2
  - image: sel232.png
    when:
      black: 2
      red: 2
      green: 3
      blue: 2
  - image: pix233.png
    when:
      black: 0
      red: 2
      green: 3
      blue: 3
  - image: pix233.png
    when:
      black: 1
      red: 2
      green: 3
      blue: 3
  - image: sel233.png
    when:
      black: 2
      red: 2
      green: 3
      blue: 3
  - image: pix300.png
    when:
      black: 0
      red: 3
      green: 0
      blue: 0
  - image: pix300.png
    when:
      black: 1
      red: 3
      green: 0
      blue: 0
  - image: sel300.png
    when:
      black: 2
      red: 3
      green: 0
      blue: 0
  - image: pix301.png
    when:
      black: 0
      red: 3
      green: 0
      blue: 1
  - image: pix301.png
    when:
      black: 1
      red: 3
      green: 0
      blue: 1
  - image: sel301.png
    when:
      black: 2
      red: 3
      green: 0
      blue: 1
  - image: pix302.png
    when:
      black: 0
      red: 3
      green: 0
      blue: 2
  - image: pix302.png
    when:
      black: 1
      red: 3
      green: 0
      blue: 2
  - image: sel302.png
    when:
      black: 2
      red: 3
      green: 0
      blue: 2
  - image: pix303.png
    when:
      black: 0
      red: 3
      green: 0
      blue: 3
  - image: pix303.png
    when:
      black: 1
      red: 3
      green: 0
      blue: 3
  - image: sel303.png
    when:
      black: 2
      red: 3
      green: 0
      blue: 3
  - image: pix310.png
    when:
      black: 0
      red: 3
      green: 1
      blue: 0
  - image: pix310.png
    when:
      black: 1
      red: 3
      green: 1
      blue: 0
  - image: sel310.png
    when:
      black: 2
      red: 3
      green: 1
      blue: 0
  - image: pix311.png
    when:
      black: 0
      red: 3
      green: 1
      blue: 1
  - image: pix311.png
    when:
      black: 1
      red: 3
      green: 1
      blue: 1
  - image: sel311.png
    when:
      black: 2
      red: 3
      green: 1
      blue: 1
  - image: pix312.png
    when:
      black: 0
      red: 3
      green: 1
      blue: 2
  - image: pix312.png
    when:
      black: 1
      red: 3
      green: 1
      blue: 2
  - image: sel312.png
    when:
      black: 2
      red: 3
      green: 1
      blue: 2
  - image: pix313.png
    when:
      black: 0
      red: 3
      green: 1
      blue: 3
  - image: pix313.png
    when:
      black: 1
      red: 3
      green: 1
      blue: 3
  - image: sel313.png
    when:
      black: 2
      red: 3
      green: 1
      blue: 3
  - image: pix320.png
    when:
      black: 0
      red: 3
      green: 2
      blue: 0
  - image: pix320.png
    when:
      black: 1
      red: 3
      green: 2
      blue: 0
  - image: sel320.png
    when:
      black: 2
      red: 3
      green: 2
      blue: 0
  - image: pix321.png
    when:
      black: 0
      red: 3
      green: 2
      blue: 1
  - image: pix321.png
    when:
      black: 1
      red: 3
      green: 2
      blue: 1
  - image: sel321.png
    when:
      black: 2
      red: 3
      green: 2
      blue: 1
  - image: pix322.png
    when:
      black: 0
      red: 3
      green: 2
      blue: 2
  - image: pix322.png
    when:
      black: 1
      red: 3
      green: 2
      blue: 2
  - image: sel322.png
    when:
      black: 2
      red: 3
      green: 2
      blue: 2
  - image: pix323.png
    when:
      black: 0
      red: 3
      green: 2
      blue: 3
  - image: pix323.png
    when:
      black: 1
      red: 3
      green: 2
      blue: 3
  - image: sel323.png
    when:
      black: 2
      red: 3
      green: 2
      blue: 3
  - image: pix330.png
    when:
      black: 0
      red: 3
      green: 3
      blue: 0
  - image: pix330.png
    when:
      black: 1
      red: 3
      green: 3
      blue: 0
  - image: sel330.png
    when:
      black: 2
      red: 3
      green: 3
      blue: 0
  - image: pix331.png
    when:
      black: 0
      red: 3
      green: 3
      blue: 1
  - image: pix331.png
    when:
      black: 1
      red: 3
      green: 3
      blue: 1
  - image: sel331.png
    when:
      black: 2
      red: 3
      green: 3
      blue: 1
  - image: pix332.png
    when:
      black: 0
      red: 3
      green: 3
      blue: 2
  - image: pix332.png
    when:
      black: 1
      red: 3
      green: 3
      blue: 2
  - image: sel332.png
    when:
      black: 2
      red: 3
      green: 3
      blue: 2
  - image: pix333.png
    when:
      black: 0
      red: 3
      green: 3
      blue: 3
  - image: pix333.png
    when:
      black: 1
      red: 3
      green: 3
      blue: 3
  - image: sel333.png
    when:
      black: 2
      red: 3
      green: 3
      blue: 3