library:
  visible: true
source:
  visible: true
  percentage: 0.5499552292263611
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: true
    can_change_initial_board_source: true
    can_edit_board: true
    can_view_size_section: true
    can_view_attire_section: true
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: true
  active: instantaneous
attire:
  visible: true
  user_permissions:
    can_toggle_visibility: true
  active: RGB
link: ''
initialDescription: true
customErrors: null
name: Paint
